version: '3.8'

services:
  dataops-app:
    build: .
    container_name: 02-DataOps-UnitTesting
    volumes:
      - .:/app
    tty: true          # <-- TAMBAHKAN BARIS INI (Biar kontainer standby)
    command: tail -f /dev/null
    environment:
      - ENV=development